### ISSUE TITLE
Processing responses from PT

### ISSUE THREAD

**Issue by accordioff** [karolyi/py3-ecrterm#4]
Dear Karolyi,

I dare to ask another question. My goal is to futher process results from an authorisation in my application like result_code, receipt number or card_type. I identified "listener" as possible solution. However, my attempts resulted in "object is not callable".
Could you supply an example how to do it correctly?

PS: Coffee is on the way :-)

Cheers

**Comment by karolyi** [comment]
Hey, thanks for the coffee :) and also the answer on the other issue, with business as usual, I don't really have a lot of time.

Looking at your question, I must say I didn't really develop with this module lately (what I did with it works ever since, maybe I'll have another touch/update on it this year), but my hunch would be, you can issue an info query at the terminal with the transaction ID you get at the transaction return, and that would tell you the information you needed.

I'm not sure this is how it works, but when reading the ZVT documentation and experimenting with the module, I remember doing something like this.

Hope this helps, let me know if you have any results.

**Comment by accordioff** [comment]
Thanks karolyi,
I think there is a misconseption. All the information is already available if I debug in the function's history. Each funktion has a "listener" which is by default "None".

`def payment(self, amount_cent=50, listener=None):`

I figured out that the listener has to be a class on application layer which receives the returning data as it is stored in the history. So no additional requests necessary in this case.

Do you know how to construct this listener on the application side?

Thanks

**Comment by accordioff** [comment]
Nevermind, I found the solution which works perfectly for me.

I defined a class with following function to further process the authorisation results. It is given to the listener parameter.

`
    def gettrace(self, *args):

        for packet in args:
            if isinstance(packet, StatusInformation):

                result_code = packet.as_dict().get('result_code')

                if result_code == 0:
                    receipt = packet.as_dict().get('receipt')
                    amount = packet.as_dict().get('amount')
                    currency_code = packet.as_dict().get('currency_code')
                    card_number = packet.as_dict().get('card_number')
                    trace_number = packet.as_dict().get('trace_number')
                    card_type = packet.as_dict().get('card_type')
                    card_name = packet.as_dict().get('card_name')
                    card_operator = packet.as_dict().get('card_operator')
`
